from django.urls import path

from .admin_views import (
    AdminDashboardView,
    AdminIotStatusView,
    AdminLogsView,
    AdminProviderCheckView,
    AdminProvidersStatusView,
    AdminRaceStatsView,
)
from .dwd_views import (
    AdminDWDApplicationApproveView,
    AdminDWDApplicationDetailView,
    AdminDWDApplicationRejectView,
    AdminDWDApplicationsView,
    AdminDWDDeviceActionView,
    AdminDWDDeviceDetailView,
    AdminDWDDeviceEventsView,
    AdminDWDDevicesView,
    AdminDWDProvisioningMarkSentView,
    AdminDWDProvisioningView,
    AdminDWDUserDetailView,
    AdminDWDUserRoleView,
    AdminDWDUsersView,
    DWDProviderApplicationDetailView,
    DWDProviderApplicationListCreateView,
    ProviderDashboardView,
)
from .views import (
    AIOutfitRecommendationView,
    GeocodeView,
    StationHistoryView,
    StationLatestView,
    StationReadingIngestView,
    WeatherHistoryView,
    WeatherView,
    health,
)

urlpatterns = [
    path("health", health, name="health"),
    path("admin/dashboard/", AdminDashboardView.as_view(), name="admin_dashboard"),
    path("admin/providers/status/", AdminProvidersStatusView.as_view(), name="admin_providers_status"),
    path("admin/providers/check/", AdminProviderCheckView.as_view(), name="admin_provider_check"),
    path("admin/race/stats/", AdminRaceStatsView.as_view(), name="admin_race_stats"),
    path("admin/iot/status/", AdminIotStatusView.as_view(), name="admin_iot_status"),
    path("admin/logs/", AdminLogsView.as_view(), name="admin_logs"),
    path("admin/dwd/users/", AdminDWDUsersView.as_view(), name="admin_dwd_users"),
    path("admin/dwd/users/<int:pk>/", AdminDWDUserDetailView.as_view(), name="admin_dwd_user_detail"),
    path("admin/dwd/users/<int:pk>/role/", AdminDWDUserRoleView.as_view(), name="admin_dwd_user_role"),
    path("admin/dwd/applications", AdminDWDApplicationsView.as_view(), name="admin_dwd_applications_no_slash"),
    path("admin/dwd/applications/", AdminDWDApplicationsView.as_view(), name="admin_dwd_applications"),
    path(
        "admin/dwd/applications/<int:pk>/",
        AdminDWDApplicationDetailView.as_view(),
        name="admin_dwd_application_detail",
    ),
    path(
        "admin/dwd/applications/<int:pk>/approve/",
        AdminDWDApplicationApproveView.as_view(),
        name="admin_dwd_application_approve",
    ),
    path(
        "admin/dwd/applications/<int:pk>/reject/",
        AdminDWDApplicationRejectView.as_view(),
        name="admin_dwd_application_reject",
    ),
    path("admin/dwd/devices", AdminDWDDevicesView.as_view(), name="admin_dwd_devices_no_slash"),
    path("admin/dwd/devices/", AdminDWDDevicesView.as_view(), name="admin_dwd_devices"),
    path("admin/dwd/devices/<int:pk>/", AdminDWDDeviceDetailView.as_view(), name="admin_dwd_device_detail"),
    path("admin/dwd/devices/<int:pk>/action/", AdminDWDDeviceActionView.as_view(), name="admin_dwd_device_action"),
    path("admin/dwd/device-events/", AdminDWDDeviceEventsView.as_view(), name="admin_dwd_device_events"),
    path("admin/dwd/provisioning", AdminDWDProvisioningView.as_view(), name="admin_dwd_provisioning_no_slash"),
    path("admin/dwd/provisioning/", AdminDWDProvisioningView.as_view(), name="admin_dwd_provisioning"),
    path(
        "admin/dwd/provisioning/<int:pk>/mark-sent/",
        AdminDWDProvisioningMarkSentView.as_view(),
        name="admin_dwd_provisioning_mark_sent",
    ),
    path("provider-applications", DWDProviderApplicationListCreateView.as_view(), name="dwd_applications_no_slash"),
    path("provider-applications/", DWDProviderApplicationListCreateView.as_view(), name="dwd_applications"),
    path("provider-applications/<int:pk>/", DWDProviderApplicationDetailView.as_view(), name="dwd_application_detail"),
    path("provider-dashboard/", ProviderDashboardView.as_view(), name="provider_dashboard"),
    path("geocode", GeocodeView.as_view(), name="geocode"),
    path("geocode/", GeocodeView.as_view(), name="geocode_slash"),
    path("weather", WeatherView.as_view(), name="weather"),
    path("weather/", WeatherView.as_view(), name="weather_slash"),
    path("weather/history", WeatherHistoryView.as_view(), name="weather_history"),
    path("weather/history/", WeatherHistoryView.as_view(), name="weather_history_slash"),
    path("ai/outfit-recommendation", AIOutfitRecommendationView.as_view(), name="ai_outfit_recommendation"),
    path("ai/outfit-recommendation/", AIOutfitRecommendationView.as_view(), name="ai_outfit_recommendation_slash"),
    path("station/readings", StationReadingIngestView.as_view(), name="station_reading_ingest"),
    path("station/readings/", StationReadingIngestView.as_view(), name="station_reading_ingest_slash"),
    path("station/latest", StationLatestView.as_view(), name="station_latest"),
    path("station/latest/", StationLatestView.as_view(), name="station_latest_slash"),
    path("station/history", StationHistoryView.as_view(), name="station_history"),
    path("station/history/", StationHistoryView.as_view(), name="station_history_slash"),
]
