# Generated by Django 5.2.13 on 2026-04-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIOutfitRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128)),
                ('hour_bucket', models.DateTimeField(db_index=True)),
                ('temperature_c', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed_ms', models.FloatField()),
                ('precipitation_mm', models.FloatField()),
                ('condition', models.CharField(blank=True, default='', max_length=128)),
                ('model_name', models.CharField(max_length=128)),
                ('prompt_version', models.CharField(default='v1', max_length=32)),
                ('recommendation_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-hour_bucket', '-created_at'],
                'indexes': [models.Index(fields=['city', 'hour_bucket'], name='server_aiou_city_600570_idx')],
            },
        ),
    ]
