# Generated by Django 5.2.13 on 2026-05-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherHourlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('hour_bucket', models.DateTimeField(db_index=True)),
                ('temperature_c', models.FloatField()),
                ('pressure_hpa', models.FloatField(blank=True, null=True)),
                ('wind_speed_ms', models.FloatField()),
                ('precipitation_mm', models.FloatField()),
                ('observed_at', models.DateTimeField()),
                ('provider', models.CharField(max_length=64)),
                ('data_source', models.CharField(choices=[('external_api', 'External API'), ('iot_mqtt', 'IoT MQTT')], default='external_api', max_length=32)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-hour_bucket', '-updated_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude', 'hour_bucket'], name='server_weat_latitud_4bea77_idx'), models.Index(fields=['data_source', 'hour_bucket'], name='server_weat_data_so_15e80a_idx')],
                'constraints': [models.UniqueConstraint(fields=('latitude', 'longitude', 'hour_bucket', 'data_source'), name='unique_weather_hourly_snapshot')],
            },
        ),
    ]
