# Generated by Django 5.2.13 on 2026-05-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_weatherhourlysnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStationReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(db_index=True, default='arduino-1', max_length=64)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField()),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('pressure_hpa', models.FloatField(blank=True, null=True)),
                ('wind_speed_ms', models.FloatField(default=0.0)),
                ('precipitation_mm', models.FloatField(default=0.0)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-observed_at', '-created_at'],
                'indexes': [models.Index(fields=['station_id', 'observed_at'], name='server_weat_station_edfed4_idx')],
            },
        ),
    ]
