# Generated by Django 5.2.13 on 2026-05-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_weatherstationreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('disabled', 'Disabled'), ('not_configured', 'Not configured')], default='not_configured', max_length=32)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True, null=True)),
                ('last_response_ms', models.FloatField(blank=True, null=True)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('total_response_ms', models.FloatField(default=0.0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('win_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RaceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=32)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
                'indexes': [models.Index(fields=['winner', 'started_at'], name='server_race_winner_3eab28_idx'), models.Index(fields=['status', 'started_at'], name='server_race_status_d8c643_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], db_index=True, default='INFO', max_length=16)),
                ('event', models.CharField(db_index=True, max_length=128)),
                ('message', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['source', 'timestamp'], name='server_syst_source_d7e0d0_idx'), models.Index(fields=['event', 'timestamp'], name='server_syst_event_430622_idx')],
            },
        ),
    ]
