# Generated by Django 5.2.13 on 2026-05-10 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_providerhealth_racerun_systemevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DWDProviderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(blank=True, default='', max_length=128)),
                ('region', models.CharField(blank=True, default='', max_length=128)),
                ('address_comment', models.TextField(blank=True, default='')),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_dwd_provider_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dwd_provider_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DWDDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=64, unique=True)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(blank=True, default='', max_length=128)),
                ('region', models.CharField(blank=True, default='', max_length=128)),
                ('address_comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dwd_devices', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='server.dwdproviderapplication')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DWDProvisioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmware_type', models.CharField(choices=[('serial_bridge', 'Serial bridge'), ('esp01_wifi', 'ESP-01 Wi-Fi'), ('ethernet_shield', 'Ethernet shield')], max_length=32)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=64)),
                ('instruction_text', models.TextField()),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged')], db_index=True, default='pending', max_length=32)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_channel', models.CharField(choices=[('email', 'Email'), ('manual', 'Manual')], default='manual', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_records', to='server.dwdproviderapplication')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioning_records', to='server.dwddevice')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_dwd_provisioning_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dwd_provisioning_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='dwdproviderapplication',
            index=models.Index(fields=['status', 'created_at'], name='server_dwdp_status_281265_idx'),
        ),
        migrations.AddIndex(
            model_name='dwdproviderapplication',
            index=models.Index(fields=['city', 'status'], name='server_dwdp_city_e365d8_idx'),
        ),
        migrations.AddIndex(
            model_name='dwddevice',
            index=models.Index(fields=['owner', 'status'], name='server_dwdd_owner_i_8c34b3_idx'),
        ),
        migrations.AddIndex(
            model_name='dwddevice',
            index=models.Index(fields=['city', 'status'], name='server_dwdd_city_86accd_idx'),
        ),
        migrations.AddIndex(
            model_name='dwdprovisioning',
            index=models.Index(fields=['firmware_type', 'delivery_status'], name='server_dwdp_firmwar_58b70d_idx'),
        ),
        migrations.AddIndex(
            model_name='dwdprovisioning',
            index=models.Index(fields=['user', 'delivery_status'], name='server_dwdp_user_id_2c547d_idx'),
        ),
    ]
