# Generated by Django 5.2.13 on 2026-05-10 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_dwdproviderapplication_dwddevice_dwdprovisioning_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DWDDeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('registered', 'Registered'), ('activated', 'Activated'), ('heartbeat', 'Heartbeat'), ('data_ingest', 'Data ingest'), ('auth_failed', 'Auth failed'), ('offline_detected', 'Offline detected'), ('blocked', 'Blocked'), ('settings_changed', 'Settings changed'), ('error', 'Error')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='dwddevice',
            name='device_code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dwddevice',
            name='firmware_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='dwddevice',
            name='firmware_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='dwddevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dwddevice',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dwddevice',
            name='last_data_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dwddevice',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dwddevice',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dwddevice',
            name='last_request_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dwddevice',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dwddevice',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dwddevice',
            name='token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='dwdproviderapplication',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dwdproviderapplication',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='dwdprovisioning',
            name='internal_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dwddevice',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('blocked', 'Blocked')], db_index=True, default='inactive', max_length=32),
        ),
        migrations.AlterField(
            model_name='dwdproviderapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='dwdprovisioning',
            name='delivery_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('firmware_assigned', 'Firmware assigned'), ('instruction_ready', 'Instruction ready'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged')], db_index=True, default='not_started', max_length=32),
        ),
        migrations.AddIndex(
            model_name='dwddevice',
            index=models.Index(fields=['firmware_type', 'status'], name='server_dwdd_firmwar_9a0863_idx'),
        ),
        migrations.AddIndex(
            model_name='dwddevice',
            index=models.Index(fields=['last_seen_at', 'status'], name='server_dwdd_last_se_e1fc0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='dwdproviderapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user',), name='unique_pending_dwd_application_per_user'),
        ),
        migrations.AddField(
            model_name='dwddeviceevent',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='server.dwddevice'),
        ),
        migrations.AddIndex(
            model_name='dwddeviceevent',
            index=models.Index(fields=['device', 'created_at'], name='server_dwdd_device__c251ec_idx'),
        ),
        migrations.AddIndex(
            model_name='dwddeviceevent',
            index=models.Index(fields=['event_type', 'created_at'], name='server_dwdd_event_t_6337d1_idx'),
        ),
        migrations.AddIndex(
            model_name='dwddeviceevent',
            index=models.Index(fields=['severity', 'created_at'], name='server_dwdd_severit_663b81_idx'),
        ),
    ]
