# Generated by Django 5.2.13 on 2026-05-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_dwddeviceevent_dwddevice_device_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dwdproviderapplication',
            name='unique_pending_dwd_application_per_user',
        ),
    ]
