# Generated by Django 5.2.13 on 2026-05-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_remove_dwdproviderapplication_unique_pending_dwd_application_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedWeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('location', models.CharField(blank=True, default='', max_length=256)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('source', models.CharField(db_index=True, default='visual_crossing', max_length=64)),
                ('forecast_days', models.PositiveSmallIntegerField(default=7)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('normalized_daily_json', models.JSONField(blank=True, default=list)),
                ('normalized_hourly_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['source', 'latitude', 'longitude', 'forecast_days', 'expires_at'], name='server_exte_source_ad4b02_idx'), models.Index(fields=['city', 'source', 'forecast_days', 'expires_at'], name='server_exte_city_ee8424_idx')],
            },
        ),
    ]
