# Generated by Django 5.2.13 on 2026-05-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_extendedweathersnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_mode', models.CharField(choices=[('serial_bridge', 'Serial Bridge'), ('wifi_esp01', 'ESP-01 Wi-Fi'), ('ethernet_shield', 'Ethernet Shield')], default='wifi_esp01', max_length=32)),
                ('serial_enabled', models.BooleanField(default=False)),
                ('serial_port', models.CharField(blank=True, default='COM3', max_length=128)),
                ('baud_rate', models.PositiveIntegerField(default=9600)),
                ('serial_status', models.CharField(choices=[('disabled', 'Disabled'), ('disconnected', 'Disconnected'), ('connected', 'Connected'), ('error', 'Error')], default='disabled', max_length=32)),
                ('serial_last_error', models.TextField(blank=True, default='')),
                ('serial_last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IoT configuration',
                'verbose_name_plural': 'IoT configuration',
            },
        ),
        migrations.AddField(
            model_name='weatherstationreading',
            name='source',
            field=models.CharField(choices=[('serial_bridge', 'Serial Bridge'), ('wifi_esp01', 'ESP-01 Wi-Fi'), ('ethernet_shield', 'Ethernet Shield')], db_index=True, default='wifi_esp01', max_length=32),
        ),
        migrations.AddIndex(
            model_name='weatherstationreading',
            index=models.Index(fields=['source', 'observed_at'], name='server_weat_source_cd7bc4_idx'),
        ),
    ]
