# Generated by Django 5.2.13 on 2026-05-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_iotconfiguration_weatherstationreading_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotconfiguration',
            name='linked_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iot_configurations', to='server.dwddevice'),
        ),
        migrations.AddField(
            model_name='weatherstationreading',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='server.dwddevice'),
        ),
        migrations.AddIndex(
            model_name='weatherstationreading',
            index=models.Index(fields=['device', 'observed_at'], name='server_weat_device__9d9918_idx'),
        ),
    ]
