# Generated by Django 5.2.13 on 2026-05-31 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_iotconfiguration_linked_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstationreading',
            name='request_ip',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='weatherstationreading',
            name='request_latency_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StationRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(db_index=True, default='arduino-1', max_length=64)),
                ('request_ip', models.CharField(blank=True, default='', max_length=64)),
                ('request_latency_ms', models.FloatField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('accepted', models.BooleanField(db_index=True, default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='server.weatherstationreading')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['station_id', 'created_at'], name='server_stat_station_7bcb01_idx'), models.Index(fields=['accepted', 'created_at'], name='server_stat_accepte_63d7e6_idx')],
            },
        ),
    ]
