# Generated by Django 5.2.13 on 2026-05-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_weatherstationreading_request_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotconfiguration',
            name='mqtt_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iotconfiguration',
            name='mqtt_host',
            field=models.CharField(blank=True, default='127.0.0.1', max_length=255),
        ),
        migrations.AddField(
            model_name='iotconfiguration',
            name='mqtt_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='iotconfiguration',
            name='mqtt_last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iotconfiguration',
            name='mqtt_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='iotconfiguration',
            name='mqtt_port',
            field=models.PositiveIntegerField(default=1883),
        ),
        migrations.AddField(
            model_name='iotconfiguration',
            name='mqtt_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('disconnected', 'Disconnected'), ('connected', 'Connected'), ('error', 'Error')], default='disabled', max_length=32),
        ),
        migrations.AddField(
            model_name='iotconfiguration',
            name='mqtt_topic',
            field=models.CharField(blank=True, default='weather/station', max_length=255),
        ),
        migrations.AddField(
            model_name='iotconfiguration',
            name='mqtt_username',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='iotconfiguration',
            name='connection_mode',
            field=models.CharField(choices=[('serial_bridge', 'Serial Bridge'), ('wifi_esp01', 'ESP-01 Wi-Fi'), ('ethernet_shield', 'Ethernet Shield'), ('mqtt', 'MQTT')], default='wifi_esp01', max_length=32),
        ),
        migrations.AlterField(
            model_name='weatherstationreading',
            name='source',
            field=models.CharField(choices=[('serial_bridge', 'Serial Bridge'), ('wifi_esp01', 'ESP-01 Wi-Fi'), ('ethernet_shield', 'Ethernet Shield'), ('mqtt', 'MQTT')], db_index=True, default='wifi_esp01', max_length=32),
        ),
    ]
